---
- name: copy
  hosts: atm-test
  become: true
  become_user: ubuntu
  gather_facts: true
  tasks:
    - name: "copy file"
      copy: src="../cert.pem" dest="~/fogbow-site-probe"
    - name: "copy file"
      copy: src="../probe-fogbow.conf" dest="~/fogbow-site-probe"